### ISSUE TITLE
How to represent replayed games or sets?

### ISSUE THREAD

**Issue by jakemingolla** [openbracketformat/openbracketformat#4]
Games (or even Sets) will occasionally need to be replayed (e.g. some setting has an incorrect value, improper stage selection, etc.). How will this be represented in the schema?

`gameNumber` is an increasing integer, but it doesn't provide any insight as to the total number of expected games vs. the total number of games in reality. I think it might make sense for a decoupling of `gameNumber` as both a chronological counter of games as well as an identifier to disambiguate games

**Comment by RLHerbert** [comment]
Byes, defaults, disqualifications, etc. should also be considered.

**Comment by VestboyMyst** [comment]
Replayed games is an interesting case we did not consider. Byes/DQs are also smart options to include.

**Comment by jschnei** [comment]
Some thoughts (since this issue seems to touch on a couple different points):
- Replayed games is an interesting edge case. Perhaps the easiest solution is not to record replayed games at all in an OBF file. This would match e.g. the behavior of sites like Challonge, where as far as I am aware they don't store information about games/sets that were replayed (incorrect results are generally just overwritten). But we can also add some sort of status field to mark a game / set as "invalid" or "replayed".
- The total number of "expected" games in a set is something that can currently be specified using the `setFormat` field (e.g. is this set "best of 3" or "best of 5"?). Re: decoupling, we could change `gameNumber` to allow for any sort of unique identifier instead of a chronological counter; is there a compelling use case for this?
- Byes/defaults/disqualifications are something we should definitely have an option to specify somehow. I'll try to think of a good way to record this (my first instinct is to add this to set.status, but I'm not completely happy with that).

**Comment by VestboyMyst** [comment]
Our current stance on this is that you should record the final set data, and OBF will not distinguish between replayed sets. DQs have been addressed in the last update,
